### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by wasamasa** [ajgrf/edwina#1]
You may want to change the name as it's pretty much universally recognized to be this project: https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-user/Edwin.html

**Comment by ajgrf** [comment]
Current plan is to rename it to Edwina. It's already on MELPA as Edwin though, so I need a transition plan instead of just a search and replace.

**Comment by ajgrf** [comment]
Closed in 604c28766db274835e28c1aeaccbcf14d0355ce9.
